### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by johndpope** [leomaurodesenv/smm-course-viewer#1]
<img width="1053" alt="screen shot 2019-02-20 at 09 06 17" src="https://user-images.githubusercontent.com/289994/53050999-d3b18c80-34ee-11e9-9081-ab600cb316c5.png">

**Comment by johndpope** [comment]
I can't seem to open any course file / only the one that loads.

**Comment by johndpope** [comment]
fyi https://github.com/RoadrunnerWMC/Metamaker

**Comment by leomaurodesenv** [comment]
> <img alt="screen shot 2019-02-20 at 09 06 17" width="1053" src="https://user-images.githubusercontent.com/289994/53050999-d3b18c80-34ee-11e9-9081-ab600cb316c5.png">

Thanks for testing the project.
I already fix the problem, see [release](https://github.com/leomaurodesenv/smm-course-viewer/releases/).

**Comment by leomaurodesenv** [comment]
> I can't seem to open any course file / only the one that loads.

I had tested with some courses, you can see them in `/course-examples/`.
- Can you send me your course? _(Note only works in Super Mario Maker Wii U)_   
This is my email: leo.mauro.desenv@gmail.com

**Comment by johndpope** [comment]
i downloaded from here - https://smmdb.ddns.net/courses

**Comment by leomaurodesenv** [comment]
I tested now with the course [Bouncy Surroundings by Stain](https://smmdb.ddns.net/api/downloadcourse?id=5c6c4b73511d13f64d78441c&type=zip) from the SMMDB.

![screenshot_2019-02-20 smmcourseviewer - demonstration](https://user-images.githubusercontent.com/11961778/53089258-d1e5ca00-34ea-11e9-8b5a-33da88ac535d.png)

Steps:
1. Extract the ZIP file
2. In smm-course-viewer > Browse > select the `course_data.cdt`file
3. Enjoy!
